module.exports = {
    trailingComma: 'all',
    tabWidth: 2,
    semi: true,
    singleQuote: true,
    printWidth: 100,
    bracketSameLine: false,
    arrowParens: 'always',
    jsxSingleQuote: false,
    bracketSpacing: true,
    singleAttributePerLine: false,
    proseWrap: 'preserve',
    plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
    importOrder: [
        '<TYPES>',
        '',
        '^next(/.*)?$',
        'react',
        '',
        '<THIRD_PARTY_MODULES>',
        '',
        '^(@/shared|@/entities|@/modules|@/widgets|@/fsd-pages|@/app)(/.*)$',
        '',
        '^(?!.*\\.(css|scss)$)[./].*$',
        '\\.(css|scss)$',
    ],
    importOrderParserPlugins: ['typescript', 'jsx'],
};
